# -*- coding: utf-8 -*-
"""quizz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5qR36dWGElpDRseuMyVaQjld-F-D2FI
"""

#create a function to run the quiz logic

questions = [
    {
        "question": "what is the  capital city of Nepal?",
        "options": ["A. Kathmandu", "B. Bhaktapur ", "C. Lalitpur",  "D. Gorkha"],
        "answer": "A"
    },
    {
        "question": "What is the highest Mountain of Nepal?",
        "options": [ "A. Mount Kanchenjunga", "B. Mount Annapurna", "C. Mount Everest", "D. Mount Dhaulagiri"],
        "answer": "C"
    },
    {
        "question": "Which river is the longest in Nepal?",
        "options": ["A. Gandaki", "B. Bagmati", "C. Karnali", "D. Koshi"],
        "answer": "C"
    },
    {
        "question": "Which city is known as the gateway of Nepal?",
        "options": [ "A. Namche Bazaar", "B. Lukla", "C. Pokhara", "D. Kathmandu"],
        "answer": "B"
    },
    {

        "question": "What is the name of the flat southern region of Nepal?",
        "options": [ "A. Hill region", "B. Mid-westen region", "C. Terai Region", "D. Mountain region"],
        "answer": "C"
    },
    {
        "question": "Which Lake is the second largest in Nepal and a popular tourist destination?",
        "options": [ "A. Phewa Lake", "B. Begnas Lake", "C. Tilicho Lake", "D. Rara Lake"],
        "answer": "A"
    },
    {
        "question": "Which national park in Nepal is a UNESCO world heritage site and home to Bengal tigers?",
        "options": [ "A. Langtang National Park", "B. Chitwan National Park", "C. Rara National Park", "C. Sagarmatha National Park"],
        "answer": "B"
    },
    {
        "question": "Which mountain range froms the northern border of Nepal?",
        "options": [ "A. Himalayas", "B. Alps", "C. Rockies", "D. Andes"],
        "answer": "A"

    },
    {
        "question": "Which valley is considered the cultural and historical heart of Nepal?",
        "options": [ "A. Solukhumbu Valley", "B. Pokhara Valley", "C. Kathmandu Valley", "D. Terai Valley"],
        "answer": "C"

    },
    {
        "question": "Which region of Nepal is most prone to landslide and eroison due to steep terrain?",
        "options": [ "A. Mountain Region", "B. Hill Region", "C. Terai Region", "D. Mid-western Region"],
        "answer": "B"

    },
    {
        "question": "Which river basin is crucial for hydroelectric power generation in Nepal?",
        "options": [ "A. Bagmati Basin", "B. Karnali Basin", "C. Gandaki Basin", "D. Koshi Basin"],
        "answer": "C"

    }
]

import streamlit as st
st.title("Know about 🇳🇵 ")
st.markdown("**Created by: Ashish** ✨")
score = 0
for i, q in enumerate(questions):
    st.subheader(f"Q{i+1}: {q['question']}")
    user_answer = st.radio("Choose your answer:", q["options"], key=i)

    if st.button(f"Submit Q{i+1}", key=f"submit_{i}"):
        if user_answer.startswith(q["answer"]):
            st.success("✅ Correct!")
            score += 1
        else:
            st.error(f"❎ Wrong! The correct answer was {q['answer']}")

st.write(f"### Your final score is: {score}/{len(questions)}")

import datetime
import streamlit as st

def save_score(username, score, total_questions):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open("quiz_scores.txt", "a") as file:
        file.write(f"{timestamp} | {username} | Score: {score}/{total_questions}\n")

# Ask for user's name
username = st.text_input("Enter your name to save your score:")

# Show save button
if st.button("Save My Score"):
    save_score(username, score, len(questions))
    st.success("✅ Your score has been saved!")

